Repository Neovici/cosmoz-i18next, pull requests merged in 2019-05, with the labels that each got.

#14 9 - Update to Polymer 2.x - part 3
  cosmoz-i18next.js
  cosmoz-t.html
  demo/index.html
Labels: 2.x, enhancement, help wanted

#16 Components, Test, converting to class-style
  analysis.json
  cosmoz-i18next.js
  cosmoz-t.html
  test/basic.html
Labels: 2.x, enhancement

#20 (dev) remove `sync-npm` and `--variants`
  package-lock.json
  package.json
Labels: enhancement

#23 (dev) old travis config
  .travis.yml
Labels: enhancement
