Repository Neovici/cosmoz-i18next, pull requests merged in 2020-04, with the labels that each got.

#48 ci: upgrade repo, make reusable, extend tests
  .codeclimate.yml
  .github/karma-problem-matcher.json
  .github/workflows/workflow.yml
  .gitignore
  .vscode/settings.json
  CONTRIBUTING.md
  analysis.json
  cosmoz-i18next.js
  cosmoz-t.js
  demo/index.html
  demo/x-translatable.js
  es-dev-server.config.js
  index.html
  karma.conf.js
  package-lock.json
  package.json
  polymer.json
  test/basic.html
  test/basic.test.js
  test/index.html
  test/translations.json
  wct.conf.json
Labels: enhancement

#50 feat: upgrade i18next dependency
  cosmoz-i18next.js
  package-lock.json
  package.json
  test/basic.test.js
Labels: dependencies, enhancement

#51 fix: adjust API for updating language resources
  cosmoz-i18next.js
  test/basic.test.js
Labels: bug

#54 feat: allow passing i18next settings to the i18n.t call
  cosmoz-i18next.js
  test/basic.test.js
Labels: enhancement
